# Dependabot are scheduled to avoid contention with normal workday CI usage. We
# start running updates at 10AM UTC (2AM PST).
version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
      time: "10:00"
      timezone: "UTC"
    allow:
      - dependency-type: all
    groups:
      kube:
        patterns:
          - k8s-openapi
          - kube
          - kube-*
        update-types: [major, minor]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: friday
      time: "03:00"
      timezone: Etc/UTC
